/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IAllowanceTransfer {
  export type PermitDetailsStruct = {
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    expiration: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
  };

  export type PermitDetailsStructOutput = [
    string,
    BigNumber,
    number,
    number
  ] & { token: string; amount: BigNumber; expiration: number; nonce: number };

  export type PermitBatchStruct = {
    details: IAllowanceTransfer.PermitDetailsStruct[];
    spender: PromiseOrValue<string>;
    sigDeadline: PromiseOrValue<BigNumberish>;
  };

  export type PermitBatchStructOutput = [
    IAllowanceTransfer.PermitDetailsStructOutput[],
    string,
    BigNumber
  ] & {
    details: IAllowanceTransfer.PermitDetailsStructOutput[];
    spender: string;
    sigDeadline: BigNumber;
  };
}

export declare namespace IWallet {
  export type UserOpStruct = {
    to: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
  };

  export type UserOpStructOutput = [string, BigNumber, string] & {
    to: string;
    amount: BigNumber;
    data: string;
  };

  export type TradeInfoStruct = {
    _token0: PromiseOrValue<string>;
    _token1: PromiseOrValue<string>;
    _feeToken: PromiseOrValue<string>;
    _amountIn: PromiseOrValue<BigNumberish>;
    _gasPrice: PromiseOrValue<BigNumberish>;
  };

  export type TradeInfoStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber
  ] & {
    _token0: string;
    _token1: string;
    _feeToken: string;
    _amountIn: BigNumber;
    _gasPrice: BigNumber;
  };
}

export interface IWalletInterface extends utils.Interface {
  functions: {
    "deposit(uint256,address,address,address,address,address,((address,uint160,uint48,uint48)[],address,uint256),uint256,bytes)": FunctionFragment;
    "exec((address,uint256,bytes)[],bytes,address,address)": FunctionFragment;
    "getTradeDetails(uint256)": FunctionFragment;
    "nonce()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deposit" | "exec" | "getTradeDetails" | "nonce"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      IAllowanceTransfer.PermitBatchStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "exec",
    values: [
      IWallet.UserOpStruct[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeDetails",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTradeDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;

  events: {
    "LogCall(address,uint256,bytes)": EventFragment;
    "LogReceivedEther(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogCall"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogReceivedEther"): EventFragment;
}

export interface LogCallEventObject {
  _contract: string;
  _value: BigNumber;
  _data: string;
}
export type LogCallEvent = TypedEvent<
  [string, BigNumber, string],
  LogCallEventObject
>;

export type LogCallEventFilter = TypedEventFilter<LogCallEvent>;

export interface LogReceivedEtherEventObject {
  _from: string;
  _amount: BigNumber;
}
export type LogReceivedEtherEvent = TypedEvent<
  [string, BigNumber],
  LogReceivedEtherEventObject
>;

export type LogReceivedEtherEventFilter =
  TypedEventFilter<LogReceivedEtherEvent>;

export interface IWallet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWalletInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _feeAsset: PromiseOrValue<string>,
      _outputToken: PromiseOrValue<string>,
      _user: PromiseOrValue<string>,
      _permit2A: PromiseOrValue<string>,
      _permit: IAllowanceTransfer.PermitBatchStruct,
      _gasPrice: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    exec(
      userOps: IWallet.UserOpStruct[],
      _signature: PromiseOrValue<BytesLike>,
      weth: PromiseOrValue<string>,
      pancakeFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTradeDetails(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IWallet.TradeInfoStructOutput]>;

    nonce(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  deposit(
    _amount: PromiseOrValue<BigNumberish>,
    _token: PromiseOrValue<string>,
    _feeAsset: PromiseOrValue<string>,
    _outputToken: PromiseOrValue<string>,
    _user: PromiseOrValue<string>,
    _permit2A: PromiseOrValue<string>,
    _permit: IAllowanceTransfer.PermitBatchStruct,
    _gasPrice: PromiseOrValue<BigNumberish>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  exec(
    userOps: IWallet.UserOpStruct[],
    _signature: PromiseOrValue<BytesLike>,
    weth: PromiseOrValue<string>,
    pancakeFactory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTradeDetails(
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IWallet.TradeInfoStructOutput>;

  nonce(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _feeAsset: PromiseOrValue<string>,
      _outputToken: PromiseOrValue<string>,
      _user: PromiseOrValue<string>,
      _permit2A: PromiseOrValue<string>,
      _permit: IAllowanceTransfer.PermitBatchStruct,
      _gasPrice: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    exec(
      userOps: IWallet.UserOpStruct[],
      _signature: PromiseOrValue<BytesLike>,
      weth: PromiseOrValue<string>,
      pancakeFactory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getTradeDetails(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IWallet.TradeInfoStructOutput>;

    nonce(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LogCall(address,uint256,bytes)"(
      _contract?: PromiseOrValue<string> | null,
      _value?: null,
      _data?: null
    ): LogCallEventFilter;
    LogCall(
      _contract?: PromiseOrValue<string> | null,
      _value?: null,
      _data?: null
    ): LogCallEventFilter;

    "LogReceivedEther(address,uint256)"(
      _from?: PromiseOrValue<string> | null,
      _amount?: null
    ): LogReceivedEtherEventFilter;
    LogReceivedEther(
      _from?: PromiseOrValue<string> | null,
      _amount?: null
    ): LogReceivedEtherEventFilter;
  };

  estimateGas: {
    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _feeAsset: PromiseOrValue<string>,
      _outputToken: PromiseOrValue<string>,
      _user: PromiseOrValue<string>,
      _permit2A: PromiseOrValue<string>,
      _permit: IAllowanceTransfer.PermitBatchStruct,
      _gasPrice: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    exec(
      userOps: IWallet.UserOpStruct[],
      _signature: PromiseOrValue<BytesLike>,
      weth: PromiseOrValue<string>,
      pancakeFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTradeDetails(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nonce(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deposit(
      _amount: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _feeAsset: PromiseOrValue<string>,
      _outputToken: PromiseOrValue<string>,
      _user: PromiseOrValue<string>,
      _permit2A: PromiseOrValue<string>,
      _permit: IAllowanceTransfer.PermitBatchStruct,
      _gasPrice: PromiseOrValue<BigNumberish>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    exec(
      userOps: IWallet.UserOpStruct[],
      _signature: PromiseOrValue<BytesLike>,
      weth: PromiseOrValue<string>,
      pancakeFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTradeDetails(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
