/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IWalletFactoryInterface extends utils.Interface {
  functions: {
    "createWallet(address,uint256[2],bytes)": FunctionFragment;
    "walletAddress(address,uint256[2],bytes,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createWallet" | "walletAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createWallet",
    values: [
      PromiseOrValue<string>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "walletAddress",
    values: [
      PromiseOrValue<string>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IWalletFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWalletFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createWallet(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    walletAddress(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createWallet(
    _impl: PromiseOrValue<string>,
    pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    _call: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  walletAddress(
    _impl: PromiseOrValue<string>,
    pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    _call: PromiseOrValue<BytesLike>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createWallet(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    walletAddress(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createWallet(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    walletAddress(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createWallet(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    walletAddress(
      _impl: PromiseOrValue<string>,
      pubkey: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      _call: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
