/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface SmartWalletTypedHashInterface extends utils.Interface {
  functions: {
    "HASHED_NAME()": FunctionFragment;
    "HASHED_VERSION()": FunctionFragment;
    "TYPE_HASH()": FunctionFragment;
    "_ECDSA_WALLET_EXEC_TYPEHASH()": FunctionFragment;
    "_PERMIT_DETAILS_TYPEHASH()": FunctionFragment;
    "_PERMIT_SINGLE_TYPEHASH()": FunctionFragment;
    "_USER_OPS_TYPEHASH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "HASHED_NAME"
      | "HASHED_VERSION"
      | "TYPE_HASH"
      | "_ECDSA_WALLET_EXEC_TYPEHASH"
      | "_PERMIT_DETAILS_TYPEHASH"
      | "_PERMIT_SINGLE_TYPEHASH"
      | "_USER_OPS_TYPEHASH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "HASHED_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HASHED_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TYPE_HASH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_ECDSA_WALLET_EXEC_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_PERMIT_DETAILS_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_PERMIT_SINGLE_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_USER_OPS_TYPEHASH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "HASHED_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HASHED_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TYPE_HASH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_ECDSA_WALLET_EXEC_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_PERMIT_DETAILS_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_PERMIT_SINGLE_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_USER_OPS_TYPEHASH",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SmartWalletTypedHash extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SmartWalletTypedHashInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    HASHED_NAME(overrides?: CallOverrides): Promise<[string]>;

    HASHED_VERSION(overrides?: CallOverrides): Promise<[string]>;

    TYPE_HASH(overrides?: CallOverrides): Promise<[string]>;

    _ECDSA_WALLET_EXEC_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    _PERMIT_DETAILS_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    _PERMIT_SINGLE_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    _USER_OPS_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;
  };

  HASHED_NAME(overrides?: CallOverrides): Promise<string>;

  HASHED_VERSION(overrides?: CallOverrides): Promise<string>;

  TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  _ECDSA_WALLET_EXEC_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  _PERMIT_DETAILS_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  _PERMIT_SINGLE_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  _USER_OPS_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    HASHED_NAME(overrides?: CallOverrides): Promise<string>;

    HASHED_VERSION(overrides?: CallOverrides): Promise<string>;

    TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    _ECDSA_WALLET_EXEC_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    _PERMIT_DETAILS_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    _PERMIT_SINGLE_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    _USER_OPS_TYPEHASH(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    HASHED_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    HASHED_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    TYPE_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    _ECDSA_WALLET_EXEC_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    _PERMIT_DETAILS_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    _PERMIT_SINGLE_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    _USER_OPS_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    HASHED_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HASHED_VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TYPE_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _ECDSA_WALLET_EXEC_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _PERMIT_DETAILS_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _PERMIT_SINGLE_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _USER_OPS_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
