/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSol from "./Test.sol";
export type { testSol };
import type * as mockAmmSol from "./mockAMM.sol";
export type { mockAmmSol };
