/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as callSol from "./Call.sol";
export type { callSol };
import type * as hasherLibSol from "./HasherLib.sol";
export type { hasherLibSol };
import type * as secp256K1LibSol from "./Secp256k1Lib.sol";
export type { secp256K1LibSol };
